### ISSUE TITLE
[PE-D] Deletion of invalid index crashes the program with its exception

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-2/tp#144] opened 2022-04-01 15:09 UTC
![delete crashes.png](https://raw.githubusercontent.com/HansHengGit/ped/main/files/c673858c-4974-4f57-9ca7-89503963f84f.png)

The delete function handles valid index and negative index well, but for indexes more that the actual item in the list, it throws an exception and terminates the program which is not that user-friendly.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: HansHengGit/ped#4

**Comment by IncompetentDev** [comment] 2022-04-11 07:32
Duplicate of #143

**Comment by quitejasper** [comment] 2022-04-11 08:29
Already resolved.

**Closed by quitejasper** 2022-04-11 08:29 UTC
